feat: #7 추천 카테고리 조회
DO-NOTTO-DO/NotToDo-Spring pull request #9
Opened 2023-01-19 08:18 UTC by junjuning

## 관련이슈

- Resolved: #7

## 변경사항

## 참고사항

2023-01-20 04:37 UTC, shb03323 commented on src/main/java/sopt/nottodo/controller/EnvironmentController.java
> +        System.out.println(environmentService.getCategory());
프린트 지워주세요💚

2023-01-20 04:38 UTC, shb03323 commented on src/main/java/sopt/nottodo/service/impl/EnvironmentServiceImpl.java
> +    @Override
앤터키 눌러주세요❤

2023-01-20 04:40 UTC, shb03323 commented on src/main/java/sopt/nottodo/dto/environment/CategoryDto.java
> +    }
생성자 부분 모든 필드를 넣기보다, Category 클래스를 매개변수로 넣어서 만들어주면 어떨까
```java
public CategoryDto(Category category) {
    this.id =  category.getId();
    this.name = category.getName();
    this.image = category.getImage();
    this.activeImage = category.getActiveImage();
}
```
처럼 하면 좋을듯 합니다. ❣

2023-01-20 04:41 UTC, shb03323 requested changes
고생했어요! 말해준것만 수정하시면 좋을 것 같아요!💙

2023-01-20 07:24 UTC, hyesuuou approved these changes
고생하셨슴다 🤍

2023-01-20 07:24 UTC, hyesuuou commented on src/main/java/sopt/nottodo/auth/SecurityConfig.java
> +                .antMatchers("/auth/**", "/environment/**")
오호,, 이건 뭔가여 ..

2023-01-20 07:24 UTC, hyesuuou commented on src/main/java/sopt/nottodo/dto/environment/CategoryDto.java
> +
한줄 지워주면 더 좋을것 같슴닷 💟

2023-01-20 07:24 UTC, hyesuuou commented on src/main/java/sopt/nottodo/repository/EnvironmentRepository.java
> +//    List<RecommendCategory> findAll();
주석도 지워주면 더 좋을것 같아유 💚

2023-01-20 07:24 UTC, hyesuuou commented on src/main/java/sopt/nottodo/service/impl/EnvironmentServiceImpl.java
> +                .map(category-> new CategoryDto(category.getId(), category.getName(), category.getImage(), category.getActiveImage()))
화살표 앞에도 스페이스 쳐주면 좋을 것 같아요 ❤️

2023-01-23 08:22 UTC, junjuning commented on src/main/java/sopt/nottodo/auth/SecurityConfig.java
> +                .antMatchers("/auth/**", "/environment/**")
header에 Authorization을 제외해주기 위한,,,,추천 카테고리 조회에서는 인증부분이 필요엄서서요💗

2023-01-23 08:25 UTC, shb03323 approved these changes
굿🧡

2023-01-23 08:37 UTC, merged